cairo/cairo/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include(('shop.urls','shop'),namespace='shop')),
]

cairo/shop/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('home', views.home, name="homepage"),
    path('index/<str:dname>', views.index, name="index"),
    path('signin', views.signin, name="signin"),
    path('signinprocess', views.siginprocess, name="signinprocess"),
    path('login', views.login, name="login"),
]

cairo/shop/models.py
from django.db import models

# Create your models here.
class department(models.Model):
    department_name = models.CharField(max_length=20)
    def __str__(self):
        return self.department_name

class item(models.Model):
    department = models.ForeignKey(department, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField()
    image = models.CharField(max_length=100)
    description = models.CharField(max_length=2600)
    def __str__(self):
        return self.item_name

class details(models.Model):
    name = models.CharField(max_length=40)
    password = models.CharField(max_length=40)
    address = models.CharField(max_length=200)
    phone = models.IntegerField()
    email = models.EmailField()
    def __str__(self):
        return self.name

cairo/shop/forms.py
from django import forms
from .models import details

class signinform(forms.ModelForm):
    class Meta:
        model = details
        fields = ["name", "password", "address", "phone", "email"]
        widgets = {
        'password': forms.PasswordInput(),
    }

class loginform(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget = forms.PasswordInput())

cairo/shop/views.py
from django.shortcuts import render, reverse
from .models import department, details
from .forms import signinform,loginform
# Create your views here.
def home(request):
    return render(request, 'shop/homepage.html', context=None)

def index(request,dname):
    try:
        dept = department.objects.get(department_name=dname)
    except department.DoesNotExist:
        dept = None
    return render(request,"shop/index.html",{'dept':dept})

def signin(request):
    return render(request, 'shop/signin.html', context=None)

def siginprocess(request):
    if (request.method=="POST"):
        currentform = signinform(request.POST)
        if currentform.is_valid():
            uobj = currentform.cleaned_data
            uemail = uobj["email"]
            if(details.objects.filter(email=uemail).exists()):
                error_message = True
                return render(request, 'shop/signin.html', {'error_message': error_message})
            currentform.save()
            return render(request, 'shop/homepage.html', context=None)
    else:
        currentform = signinform()
    return render(request, 'shop/signin.html', {'currentform': currentform})


def login(request):
    if(request.method=="POST"):
        formInstance = loginform(request.POST)
        if formInstance.is_valid():
            userobj = formInstance.cleaned_data
            uemail = userobj["email"]
            upassword = userobj["password"]
            d = details.objects.get(email=uemail)
            if ((details.objects.filter(email=uemail).exists()) and (d.password == upassword)):
                return render(request, 'shop/signin.html')
            else:
                error_message=True
                return render(request, 'shop/homepage.html', {'error_message':error_message})

cairo/shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CAIRO</title>
    {% block links %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/main.css' %}">
<script src="{% static 'shop/js/main.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- Header -->

<nav id="myid" class="navbar navbar-expand-lg navbar-light ">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainnav" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>

  </button>
  <a class="navbar-brand" style="color:white;" href="#">CAIRO</a>
    <button id="loginbtn" type="button" onclick="turnon()">Log in</button>
  <div>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2 ml-4" id="searchbar" type="search" placeholder="Search" aria-label="Search" style="width:600px;">
    <button class="btn my-2 my-sm-0 py-2 fa fa-search" style="background:inherit;color:white;opacity:.3;border:1px solid" type="submit"></button>
  </form>
</div>
  <button class="btn btn-warning mx-2 my-sm-0" type="button" style="float:right;">S</button>

  <div class="collapse navbar-collapse" id="mainnav" >

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:homepage' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:index' dname="mobiles" %}">  MOBILES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:index' dname="laptops" %}">LAPTOPS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:index' dname="fashion" %}">fASHION</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:index' dname="books" %}">BOOKS</a>
      </li>
    </ul>

  </div>

</nav>
<!-- Popup Login form -->

<div id="turn" class="popupdiv">
<form class="popupform" action="{% url 'shop:login' %}" method="post">
  {% csrf_token %}
  <h3 id="popuphead">LOGIN</h3>
  <button id="xbtn" onclick="turnoff()">X</button>
<label for="email" class="labellog">email</label>
<input type="email" name="email" value="" placeholder="uname@mail.com">
<label for="password" class="labellog">password</label>
<input type="password" name="password" value="" placeholder="password">
<input type="submit" name="" class="btnlogin" value="Log In">
</form>
<a href="{% url 'shop:signin' %}">Sign In</a>
</div>
<!-- End of Popup Login form -->

<div id="lowernav">


    <ul class="px-2" id="mylist">
      <li >
        <a href="{% url 'shop:homepage' %}">HOME </a>
      </li>
      <li >
        <a href="{% url 'shop:index' dname='mobiles' %}">MOBILES</a>
      </li>
      <li >
        <a href="{% url 'shop:index' dname='laptops' %}">LAPTOPS</a>
      </li>
      <li >
        <a href="{% url 'shop:index' dname='fashion' %}">FASHION</a>
      </li>
      <li>
        <a href="{% url 'shop:index' dname='books' %}">BOOKS</a>
      </li>
    </ul>
  </div>


<!--End of Header -->


{% block content %}


{% endblock %}



<!-- Footer -->
<footer id="outfooter" class="page-footer font-small pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled"  >
          <li class="footlinks">
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->



  <!-- Footer Icons -->
  <footer class="page-footer font-small">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Grid row-->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-12 py-5">
          <div class="mb-5 flex-center" id="footericon">

            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fa fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fa fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fa fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Pinterest-->
            <a class="pin-ic">
              <i class="fa fa-pinterest fa-lg white-text fa-2x"> </i>
            </a>
          </div>
        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
    <!-- Footer Elements -->


  </footer>
  <!--End of Footer Icons -->
  <!-- Copyright -->
  <div id="infooter" class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#">Cairo.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->






<!-- End of Footer -->
</body>
</html>

cairo/shop/templates/shop/homepage.html
{% extends "base.html" %}

{% block content %}

{% if error_message %}

<script>
  alert("Invalid email or password");
</script>


{% endif %}

<h1> Hello world </h1>



Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.












{% endblock %}

cairo/shop/templates/shop/index.html
{% extends "base.html" %}
{% block links %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/index.css'  %}" >
{% endblock %}
{% block content %}
{% if dept %}

{% for d in dept.item_set.all %}

<div class="outercontent">

  <img id="myimg" class="img-responsive" src="{% static "" %}{{d.image}}" alt="Not available">
  <div class="inner">
  <h1 style="display:inline;"> {{d.item_name }}</h1>
  <h2 id="cost">&#8377;{{d.price}} </h2>
  <p> {{d.description}}</p>

  <button class="btn btn-primary" type="submit">BUY</button>
  <div style="clear:both;"></div>
  </div>
</div>

{% endfor %}
{% else %}

<h1> No items Found </h1>

{% endif %}

{% endblock %}

cairo/shop/templates/shop/signin.html
{% extends 'base.html' %}
{% block links %}
{% load static %}
<link rel="stylesheet"  type="text/css" href="{% static 'shop/css/signin.css' %}">
{% endblock %}

{% block content %}
{% if error_message %}
<script>
alert("Email Id already exists!")
</script>
{% endif %}


<div class="outerbox">
<form class="box" action="{% url 'shop:signinprocess' %}" method="post">
  {% csrf_token %}
  <h1> Sign In </h1>
  <input type="text" name="name" placeholder="Name">
  <input type="password" name="password" placeholder="Password">
  <input type="text" name="address" placeholder="Enter your address">
  <input type="number" name="phone" placeholder="Phone Number">
  <input type="email" name="email" placeholder="Email address">
  <input type="submit" value="Sign In">
</form>
</div>







{% endblock %}